In [3]:
!pip install numpy


[notice] A new release of pip is available: 25.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import numpy as np
import sys
python_list=list(range(1000))
numpy_array=np.arange(1000)
print("memory used by python list",sys.getsizeof(python_list))
print("memory used by numppy array",numpy_array.nbytes,"bytes")



memory used by python list 8056
memory used by numppy array 8000 bytes


In [18]:
import numpy as np
a=np.arange(10,30,50)
b=np.arange(20,30,70)
print(a+b)

[30]


In [1]:
# speed range
import numpy as np
import time

# Create a Python list
python_list = list(range(1000000))

# Create a NumPy array
numpy_array = np.arange(1000000)

# Python list operation
start = time.time()
python_result = [x * 2 for x in python_list]
end = time.time()
print("Python list time:", end - start, "seconds")

# NumPy array operation
start = time.time()

numpy_result = numpy_array * 2

end = time.time()

print("NumPy array time:", end - start, "seconds")

Python list time: 0.11578178405761719 seconds
NumPy array time: 0.007209300994873047 seconds


In [2]:
# Convert Python List to NumPy Array

import numpy as np

# Python list
numbers = [10, 20, 30, 40, 50]

# Convert list into NumPy array
arr = np.array(numbers)

print("Python List:")
print(numbers)

print("\nNumPy Array:")
print(arr)

Python List:
[10, 20, 30, 40, 50]

NumPy Array:
[10 20 30 40 50]


In [1]:
# ones array 1D
import numpy as np

a = np.ones((5))

print(a)

[1. 1. 1. 1. 1.]


In [2]:
#ones array 1D
import numpy as np
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
#zeroes matrix array 2D
import numpy as np

a = np.zeros((3,3))

print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# full matrix array 
import numpy as np

a = np.full((3,3),7)

print(a)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [8]:
# Numpy Zeros, Ones, and Full Arrays (2D)

import numpy as np

zeros_array = np.zeros((2, 3))
ones_array = np.ones((2, 3))
full_array = np.full((2, 3), 5)

print("Zeros:")
print(zeros_array)

print("\nOnes:")
print(ones_array)

print("\nFull:")
print(full_array)



Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Full:
[[5 5 5]
 [5 5 5]]


In [9]:
# One-Dimensional Array in NumPy

import numpy as np

# Create a 1D array
arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Array: [10 20 30 40 50]
Shape: (5,)
Size: 5
Data type: int64


In [14]:
# Reshaping an Array in NumPy

import numpy as np

# Create an array from 0 to 20
arr = np.arange(21)

print("Original array:")
print(arr)

# Reshape the array
new_arr = arr.reshape(3, 7)

print("\nReshaped array:")
print(new_arr)

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Reshaped array:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


In [2]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70])
print("original aaray:",arr)
print("elements from index 1 t0 4:",arr[1:5])
print("first 3 element:",arr[:3])
print("last 3 element:",arr[-3:])
print("every second element:",arr[::2])

original aaray: [10 20 30 40 50 60 70]
elements from index 1 t0 4: [20 30 40 50]
first 3 element: [10 20 30]
last 3 element: [50 60 70]
every second element: [10 30 50 70]


In [1]:
name = input("Enter your name: ")

if name.strip() == "":
    print("true")
else:
    print("Hello", name)

Enter your name:      


true


In [1]:
date = input("Enter date (DD-MM-YYYY): ")

day = int(date[0:2])
month = int(date[3:5])
year = int(date[6:10])

if month == 9 and day >= 1 and day <= 29:
    day = day + 1
    print(day, "-", month, "-", year)

elif month == 9 and day == 30:
    print("01-10-2025")

else:
    print("Invalid Date")

Enter date (DD-MM-YYYY):  16-09-2025


17 - 9 - 2025


In [8]:
name="hello"
print(name.upper())
print(name.endswith("o"))
print(name.appe

HELLO
True


In [1]:
import pandas as pd
import sqlite3

conn=sqlite3.connect("students.db")

data={
    "id":[1,2,3],
    "name":["amit","rahul","priya"],
    "marks":[85,90,78]
}
df=pd.DataFrame(data)
df.to_sql("students",conn,if_exists="replace",index=False)

result=pd.read_sql("select * from students",conn)
print(result)
conn.close()

   id   name  marks
0   1   amit     85
1   2  rahul     90
2   3  priya     78


In [7]:
import pandas as np
data={ "marks" :[45,50,55,60,65,70,75,200]
}

df=pd.DataFrame(data)
Q1= df["marks"].quantile(0.25)
Q3=df["marks"].quantile(0.75)
print("Q1:",Q1)
print("Q3:",Q3)
IQR= Q3-Q1
print("IQR",IQR)
lower_limit=Q1-1.5*IQR
UPPER_limit=Q3-1.5*IQR
print("lower limit",lower_limit)
print("UPPER limit",UPPER_limit)
clean_df=df[
    (df["marks"]>=lower_limit)&
    (df["marks"]<=UPPER_limit)
]
print("original data")
print(df)
print("\nafter removing")
print(clean_df)

Q1: 53.75
Q3: 71.25
IQR 17.5
lower limit 27.5
UPPER limit 45.0
original data
   marks
0     45
1     50
2     55
3     60
4     65
5     70
6     75
7    200

after removing
   marks
0     45
